name: Check and fix typos

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v2

      - name: Check speling of all the files.
        uses: bnjbvr/typos@write-changes
        with: 
          write_changes: true

      - uses: getsentry/action-git-diff-suggestions@main
        with:
          message: typos
